### ISSUE TITLE
Support for Launch Configurations and AutoScaling Groups

### ISSUE THREAD

**Issue by srijs** [frontrowed/stratosphere#1]
Hi!

I'm missing support for EC2 launch configurations and auto-scaling groups.

Any chance those could be added?

**Comment by jdreaver** [comment]
Hey, thanks for the feature request!

I added all of the Auto Scaling Group resources and resource properties I could find in the CloudFormation docs to #2. Please let me know if I missed anything else you need.

Are you using stack? If so, are you comfortable trying this out by using the commit SHA from that PR in your `stack.yaml`, or do you want me to make a minor version release to Stackage? I don't use auto scaling groups currently so I wouldn't be able to test this effectively right now, and I would like some confirmation it works on a real config before merging that PR.

**Comment by srijs** [comment]
Thanks for the quick response!

I tried out the branch and it looks good to me so far, except that I'm missing a way to add an UpdatePolicy to an auto scaling group.

**Comment by jdreaver** [comment]
Ah you're right, I totally missed UpdatePolicy. It looks like I'll have to add CreationPolicy too (CreationPolicy looks a lot easier to implement). I'll try to get to it today.

**Comment by jdreaver** [comment]
Hey @srijs, I've added the following to that branch:
* CreationPolicy
* UpdatePolicy
* An [example](https://github.com/frontrowed/stratosphere/blob/05494a048bd57e1f6cfe72134c852dc721f9a9ef/examples/auto-scaling-group.hs) that uses both of those things

Let me know if I missed anything!

**Comment by srijs** [comment]
This is awesome, thanks! I'm able to convert all of my current Troposphere templates to Stratosphere now, and am super happy about the result :)

**Comment by jdreaver** [comment]
Awesome! :smile: 

I'm going to close this, merge that branch, and make a hackage release to version 0.1.2 today. Feel free to open an issue with any other deficiencies you find! So far I've only stuck to the parts of CloudFormation we use at Front Row, but the goal is to include everything else eventually.
