### ISSUE TITLE
Stratosphere takes too much RAM to compile

### ISSUE THREAD

**Issue by jdreaver** [frontrowed/stratosphere#117]
We are starting to hit the 4 GB limit of CircleCI on newer GHC versions. In particular, compiling the big `Resources` module is gnarly. I can think of a few options:

1. Pay for a larger build machine. We are on the Freckle github org, so maybe we can just use a larger build machine and it will go to our company bill?
2. Get rid of the big `ResourceProperties` sum type. We used to want that so `FromJSON` was easier, but I highly doubt anyone even uses `FromJSON`. Even so, we could just make `ResourceProperties` opaque and have each resource produce a `ResourceProperties` product type itself.
3. Split up `stratosphere`? If we do that, `Resources.hs` will still probably take a ton of RAM unless we do option 2. This option seems highly nontrivial.
4. Get rid of `FromJSON` entirely since I doubt anyone uses it. That might make a dent in RAM.

**Comment by utdemir** [comment]
Relevant issue: https://github.com/frontrowed/stratosphere/issues/95

**Comment by andreyk0** [comment]
We are bumping into this too a bit, option (2) sounds good!

**Comment by Znack** [comment]
If we get rid of `FromJSON` we can also consider to implement #80 in new ways :)

**Comment by jdreaver** [comment]
Yeah when I compile on my laptop, even with `--fast`, `stack` barely uses memory _until_ we compile `Stratosphere.Resources`. Then we go above 4.5 GB. I'm leaning towards at removing `FromJSON` and the big resource sum type.

Thanks for the feedback everyone!

**Comment by jdreaver** [comment]
Fixed via https://github.com/frontrowed/stratosphere/pull/118  :tada: 

Simply removing `FromJSON` fixed everything. I didn't have to touch `ResourceProperties` at all (although I'm not a fan of that sum type even having to exist...).
