### ISSUE TITLE
Should cabal file be included in source control?

### ISSUE THREAD

**Issue by MichaelXavier** [frontrowed/stratosphere#16]
I noted in the README you mention that it would be nice to not have to include generated code in git for this repo (but it seems unavoidable at this point). I'm wondering if the same can be said for the .cabal file which seems to be generated from package.yaml. 

Here's my thinking: this project isn't a complete mapping of cloudformation resources yet. As a user, I'm happy to add those and submit a PR and wait for a release, but in the interim I typically vendor the project via git submodule into mine, set to point at my patched version. If I'm in a stack project it seems like everything "just works" (no surprise) and the cabal file gets generated on project build. However, on regular cabal projects, I can't build this project as a dependency because the cabal file isn't generated, so I would either have to manually go in and generate the cabal file when its updated or I'd have to clone the project elsewhere, build it, build an sdist and then unpack that into my project on every change.

I do see the problem with committing the .cabal file as they could go out of sync. I'm not positive committing it is the best solution but given that this project is especially prone to users vendoring it, its worth considering the workflow for non stack-ready projects.

**Comment by jdreaver** [comment]
Good point. Is it possible for you to run hpack manually as part of some build process? That would generate the .cabal file for you. 

You're right that the only real danger is them getting out of sync. Maybe I could add a CI command to ensure that the committed .cabal file matches the one generated by hpack.

**Comment by MichaelXavier** [comment]
Yeah a build process would probably be reasonable. The trick there is you need to get used to going from funnelling all your dev tasks through cabal to a higher level tool (like shake, for example) that will run the project build tasks for you and create any necessary files. Its mainly a question of inertia, but its probably the right thing to do.

**Comment by jdreaver** [comment]
The "build process" could be as simple as a shell script that first runs hpack, and then runs cabal. hpack is very quick, so I don't think you need something like shake.

**Comment by MichaelXavier** [comment]
Yeah, I was mostly speaking of my case: I already have other assets I have to build like javascript stuff that is a more compelling argument for shake. Hooking something like shake into the cabal build (which you can do) is way more painful and sketchy than inverting that and hooking the cabal build into the build tool (be it shake or a shell script).

**Comment by jdreaver** [comment]
Sounds good. I'll close this then. Let me know if it's super painful still without the .cabal file. 

The other solution is to keep stratosphere more up to date and not wait weeks for a release after a change :smile: I have no problem with making tiny, incremental releases, so feel free to badger me to make a release if we merge a PR.
