### ISSUE TITLE
scraper fails to scrape resource page properly

### ISSUE THREAD

**Issue by ababkin** [frontrowed/stratosphere#23]
encountered an AWS CF resource page, from which the scraper managed to scrape only first two properties and completely ignored all the rest 

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-restapi.html

**Comment by jdreaver** [comment]
Yeah the AWS docs HTML is really inconsistent at times. In fact I'm amazed the scraper works as well as it does sometimes. I'll take a look though, hopefully this page is just a fluke and they haven't changed their docs page structure too much.

**Comment by ababkin** [comment]
thanks, no rush really and not a showstopper by no means - i've added this just so it won't get lost
