### ISSUE TITLE
scraper sets "required: false" when it should be "required: true"

### ISSUE THREAD

**Issue by ababkin** [frontrowed/stratosphere#24]
For this doc: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-method.html

generates:

``` json
    {
      "Name": "AuthorizationType",
      "Type": "Text",
      "Documentation": "The method's authorization type.",
      "Required": false
    },
```

when Required should be 'true' according to the doc

**Comment by jdreaver** [comment]
Yeah it's probably because of the extra stuff after `Yes`. The scraper is not very smart.
