### ISSUE TITLE
style suggestion: newtype instead of data for DuplicateProperty

### ISSUE THREAD

**Issue by DanBurton** [frontrowed/stratosphere#38]
As seen on the Stackage build server building stratosphere-0.2.1:

```
> /tmp/stackage-build12/stratosphere-0.2.1$ dist/build/style/style
library/Stratosphere/Check.hs:17:1: Suggestion: Use newtype instead of data
Found:
  data DuplicateProperty = DuplicateProperty T.Text
                         deriving Show
Why not:
  newtype DuplicateProperty = DuplicateProperty T.Text
                            deriving Show
Note: decreases laziness
```

**Comment by jdreaver** [comment]
Oh interesting, my CI didn't show this problem. I wonder if the Stackage build is using a newer version of HLint. I'll investigate. Thanks!

**Comment by jdreaver** [comment]
Yeah, this error is indeed from the latest version of HLint (see here https://hackage.haskell.org/package/hlint-1.9.38/changelog). It's so new it's not in the nightly snapshot yet haha.

I set `hlint-1.9.38` in `extra-deps` for now, and I fixed the error. I'll make a bug-fix release soon. Thanks for reporting this!

**Comment by jdreaver** [comment]
Fixed via https://github.com/frontrowed/stratosphere/commit/7a5e559fb77bc3e2ca78ace1540da0269e50f173. I've uploaded version 0.2.2 to Hackage.
