### ISSUE TITLE
Use (Val a) as a parameters for condition Equals 

### ISSUE THREAD

**Issue by Znack** [frontrowed/stratosphere#76]
I want at first thank you for this amazing library. We are migrating our project technology stack from Python to Haskell and I was very happy to find such cool alternative for Python's Troposphere :)

Today I have encountered the first problem: now `Equals` expects two `Val Bool` as parameters: `Equals (Val Bool) (Val Bool)`. Although AWS in their docs just point its as String: [docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-conditions.html#intrinsic-function-reference-conditions-equals). Now with two bools I have no idea how to compare for example refs or strings even for basic cases like this from the docs:

```json
"UseProdCondition" : {
   "Fn::Equals": [
      {"Ref": "EnvironmentType"},
      "prod"
   ]
}
```

Here we have to compare with string "prod" and I have no idea how to play with compiler to stop it complaining.

**Comment by jdreaver** [comment]
Hey, thanks for the kind words! :smile: 

Indeed, this looks like a total oversight on my part. This should be `Val a` instead of `Val Bool`. I've opened a PR at https://github.com/frontrowed/stratosphere/pull/78
