### ISSUE TITLE
Is there a way to add AWS::CloudFormation::Init for a LaunchConfiguration

### ISSUE THREAD

**Issue by Znack** [frontrowed/stratosphere#77]
`AWS::CloudFormation::Init` is the very useful and popular property often used with LaunchConfiguration, although I couldn't figure out how to set Metadata with `AWS::CloudFormation::Init` for my instances in the stack. As I understand it should be one of the field of `Resource` along with `_resourceProperties`, `_resourceCreationPolicy`, etc fields. Could someone please advice is there some workaround to add `AWS::CloudFormation::Init` property for LaunchConfiguration ressource?

Thank you!

**Comment by jdreaver** [comment]
I think a good escape hatch here is to just add a `_resourceMetadata :: Maybe Object` field. That way you can at least add metadata, although it will be untyped in Haskell. Maybe in the future we can provide more structure here, although I don't know how much structure there could be fore `AWS::CloudFormation::Init`.

I've opened a PR at #79

**Comment by jdreaver** [comment]
Hey @Znack, I just uploaded `stratosphere` version 0.19.0 that fixes both this issue and #76. Let me know if that version fixes any problems you have, and feel free to open more issues if you find new problems. Thanks for the bug reports and feature suggestions!

**Comment by Znack** [comment]
Hello @jdreaver, I have checked the both `Equals` constructor and resource's Metadata — everything works like a charm! Thank you a lot for such quick help :)

By the way, today I encountered the another skipped AWS property: [Not](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-conditions.html#intrinsic-function-reference-conditions-not) :) I'm going to report new issue about it and suggest my help here
