### ISSUE TITLE
Where to put a sum type

### ISSUE THREAD

**Issue by timmytofu** [frontrowed/stratosphere#8]
More of a question than an issue. Today I'm also hoping to add S3 resources (bucket and policy).

http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket.html

The `AccessControl` parameter would nicely fit a sum type, rather than leaving it entirely open as `Text`, but I'm not sure where to put this, module-wise, or how to reference it. The closest example I can find is `DeletionPolicy`, but that's a parameter common to all resources, or `ConnectionDrainingPolicy` and things like it, but they're all record types.

**Comment by jdreaver** [comment]
Hmm, good call. We should probably create a new `Types` module under `library` for this, and then add it to the `Dependencies` section of a generated module's JSON file. I might take a crack at this today.

**Comment by timmytofu** [comment]
Solved by #9
