### ISSUE TITLE
Stratosphere does not export Python3.6 Runtime for AWS Lambda

### ISSUE THREAD

**Issue by utdemir** [frontrowed/stratosphere#87]
AWS documentation says it's possible to use Python3.6 as a runtime for Lambda functions: https://docs.aws.amazon.com/lambda/latest/dg/API_CreateFunction.html#SSS-CreateFunction-request-Runtime

However Stratosphere does not export this: https://www.stackage.org/haddock/lts-11.1/stratosphere-0.19.1/Stratosphere-Types.html#t:Runtime

I do not know if this is a new addition and you only need to generate the code again, or if there is something wrong with AWS's exported documentation or code generator.

**Comment by jdreaver** [comment]
Ah thanks for reporting this! I've opened a PR at #88

**Comment by utdemir** [comment]
Thank you, I appreciate the quick fix :). 

Also thanks for this project, it is the only thing which makes using CloudFormation bearable.
