### ISSUE TITLE
Template validation error: Invalid template property or properties [FormatVersion]

### ISSUE THREAD

**Issue by ababkin** [frontrowed/stratosphere#91]
looks like   
`FormatVersion` key in a CF template has been changed to `AWSTemplateFormatVersion`
I've updated my `stratosphere` to the latest `master` but it still renders templates with `FormatVersion`.

I found this, which should seemingly render the correct key, yet it is still `FormatVersion` when i run an example from the `examples` folder.
https://github.com/frontrowed/stratosphere/blob/5356dc9aca0d5d7b384ccc1d83183fa18a464719/library/Stratosphere/Helpers.hs#L47

I feel like I'm chasing my tail at this point. Any help is appreciated. Thanks

**Comment by jdreaver** [comment]
Hey @ababkin! Oof, sorry about that. It should be fixed now!

**Comment by ababkin** [comment]
This fixed it, thanks!
